### ISSUE TITLE
Utilização de text block

### ISSUE THREAD

**Issue by arthurs159** [rudzzz/java-banking-system#1]
Oi Acir, olhando seu projeto, vejo que uma parte dele, você utilizando bastante system.out, seria interessante, quando isso for ocorrer, você utilizar o text block no lugar, deixando o código mais limpo, você consegue utilizar textblock em toda essa parte do código, inclusive adicionar as variáveis também.

![image](https://user-images.githubusercontent.com/77133022/194963575-96727d11-6d00-49bb-a3b9-366c2c20347c.png)

Depois de fazer o texto você usaria o `.formatted`, da uma pesquisada, acho que vai ficar bem melhor!! : )

Qualquer dúvida, só me chamar.

**Comment by rudzzz** [comment]
Alterado para text block em vez de de System.out.println().
